# Generated by Django 3.2 on 2022-04-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_category_options"),
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_stars",
                to="catalog.item",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="star",
            field=models.IntegerField(
                choices=[
                    (0, "Ещё не оценили"),
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                default=0,
                verbose_name="Оценка",
            ),
        ),
    ]
