# Generated by Django 3.2 on 2022-03-25 10:25

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Допустимая длина 150 символов', max_length=150, verbose_name='Название')),
                ('text', models.TextField(help_text='Минимум два слова', validators=[catalog.validators.validate_brilliant], verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
