# Generated by Django 3.2 on 2022-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_item_ratings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Название"),
        ),
    ]
